  - platform: mqtt
    schema: json
    name: Sonoff Test
    state_topic: "stat/test"
    command_topic: "cmnd/test"
    brightness: true
    rgb: true
    effect: true
    effect_list: [Solid, Random]
    qos: 0